### ISSUE TITLE
А как же тариф со стоимостью за день?

### ISSUE THREAD

**Issue by coursar** [rufattabaev/tariffs#4]
https://github.com/rufattabaev/tariffs/blob/dde2389b4294187b2e7443e2438cb0cb0be41f0e/src/main/java/Tariffs.java#L4

**Comment by rufattabaev** [comment]
https://github.com/rufattabaev/tariffs/blob/dde2389b4294187b2e7443e2438cb0cb0be41f0e/src/main/java/Tariffs.java#L10

для этого создал отдельную переменную со стоимостью за день. Или так не правильно?

**Comment by coursar** [comment]
Пока норм. Потом - лучше хранить отдельно цену, отдельно единицу измерения.
